- name: Install Prometheus Slurm Exporter
  shell: "/usr/bin/go install github.com/astappiev/slurm_exporter@v0.21.0"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    PATH: "{{ ansible_env.HOME }}/go/bin:/usr/local/go/bin:{{ ansible_env.PATH }}"
  args:
    executable: /bin/bash
  register: go_install_output
  changed_when: "'no required module' not in go_install_output.stdout"

- name: Template slurm systemd service file
  template:
    src: slurm-exporter.service.j2
    dest: /etc/systemd/system/slurm-exporter.service
    owner: root
    group: root
    mode: '0644'
#  notify:
#    - Reload systemd daemon
#    - Restart Conclave Backend
